name: Check Commit Message

on:
  push:
    branches:
      - master

jobs:
  check-commit-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Check Commit Message
        run: |
          # Get the latest commit message
          commit_message=$(git log -1 --pretty=%B)

          echo "Latest commit message: $commit_message"

          # Define the regex pattern to match the required title format
          title_pattern="^.+: .+"  # Title should be in the format Task Type: Task Name

          # Define the regex pattern to match the Asana link
          asana_pattern="https://app\.asana\.com/\d+"

          # Check if the commit message matches the required format
          if ! [[ $commit_message =~ $title_pattern ]]; then
            echo "Error: The commit message must follow the format: Task Type: Task Name"
            exit 1
          fi

          # Check for Asana link in the commit message
          if ! [[ $commit_message =~ $asana_pattern ]]; then
            echo "Error: The commit message must include an Asana task link in the format: https://app.asana.com/..."
            exit 1
          fi
